graph LR
HUB_CLIENTES["HUB_CLIENTES"]:::hub
HUB_LINEAS_PEDIDOS["HUB_LINEAS_PEDIDOS"]:::hub
HUB_PAISES["HUB_PAISES"]:::hub
HUB_PARTES["HUB_PARTES"]:::hub
HUB_PEDIDOS["HUB_PEDIDOS"]:::hub
HUB_PROVEEDORES["HUB_PROVEEDORES"]:::hub
HUB_REGIONES["HUB_REGIONES"]:::hub
LNK_CLIENTES_PEDIDOS(["LNK_CLIENTES_PEDIDOS"]):::lnk
LNK_PAISES_CLIENTES(["LNK_PAISES_CLIENTES"]):::lnk
LNK_PAISES_PROVEEDORES(["LNK_PAISES_PROVEEDORES"]):::lnk
LNK_PARTES_LINEAS_PEDIDOS(["LNK_PARTES_LINEAS_PEDIDOS"]):::lnk
LNK_PEDIDOS_LINEAS_PEDIDOS(["LNK_PEDIDOS_LINEAS_PEDIDOS"]):::lnk
LNK_PROVEEDORES_LINEAS_PEDIDOS(["LNK_PROVEEDORES_LINEAS_PEDIDOS"]):::lnk
LNK_PROVEEDORES_PARTES(["LNK_PROVEEDORES_PARTES"]):::lnk
LNK_REGIONES_PAISES(["LNK_REGIONES_PAISES"]):::lnk
SAT_CLIENTES_CONTACTO{"SAT_CLIENTES_CONTACTO"}:::sat
SAT_CLIENTES_CUENTA{"SAT_CLIENTES_CUENTA"}:::sat
SAT_LINEAS_PEDIDOS{"SAT_LINEAS_PEDIDOS"}:::sat
SAT_PAISES{"SAT_PAISES"}:::sat
SAT_PARTES{"SAT_PARTES"}:::sat
SAT_PARTES_PROVEEDORES{"SAT_PARTES_PROVEEDORES"}:::sat
SAT_PEDIDOS{"SAT_PEDIDOS"}:::sat
SAT_PROVEEDORES{"SAT_PROVEEDORES"}:::sat
SAT_REGIONES{"SAT_REGIONES"}:::sat
HUB_REGIONES --> SAT_REGIONES
HUB_REGIONES --> LNK_REGIONES_PAISES
HUB_PAISES --> LNK_REGIONES_PAISES
HUB_PAISES --> SAT_PAISES
HUB_PAISES --> LNK_PAISES_PROVEEDORES
HUB_PAISES --> LNK_PAISES_CLIENTES
HUB_CLIENTES --> LNK_PAISES_CLIENTES
HUB_PROVEEDORES --> LNK_PAISES_PROVEEDORES
HUB_CLIENTES --> LNK_CLIENTES_PEDIDOS
HUB_PROVEEDORES --> SAT_PROVEEDORES
HUB_PROVEEDORES --> LNK_PROVEEDORES_PARTES
HUB_PARTES --> LNK_PROVEEDORES_PARTES
LNK_PROVEEDORES_PARTES --> LNK_PROVEEDORES_LINEAS_PEDIDOS
HUB_PARTES --> SAT_PARTES_PROVEEDORES
SAT_PROVEEDORES --> SAT_PARTES_PROVEEDORES
HUB_PARTES --> LNK_PARTES_LINEAS_PEDIDOS
HUB_PARTES --> SAT_PARTES
HUB_PEDIDOS --> LNK_CLIENTES_PEDIDOS
HUB_LINEAS_PEDIDOS --> LNK_PARTES_LINEAS_PEDIDOS
HUB_PEDIDOS --> LNK_PEDIDOS_LINEAS_PEDIDOS
HUB_LINEAS_PEDIDOS --> LNK_PEDIDOS_LINEAS_PEDIDOS
HUB_PEDIDOS --> SAT_PEDIDOS
HUB_LINEAS_PEDIDOS --> SAT_LINEAS_PEDIDOS
HUB_CLIENTES --> SAT_CLIENTES_CONTACTO
HUB_CLIENTES --> SAT_CLIENTES_CUENTA
classDef hub fill:#add8e6,stroke:#000,stroke-width:1px;
classDef lnk fill:#90ee90,stroke:#000,stroke-width:1px;
classDef sat fill:#ffffcc,stroke:#000,stroke-width:1px;