version: 2

sources:
  - name: stg
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    config:
      materialized: 'table'
    tables:
      - name: CUSTOMER
        description: "Tabla original de CLIENTES"
      - name: LINEITEM
        description: "Tabla original de LINEAS DE PEDIDOS"
      - name: NATION
        description: "Tabla original de PAISES"
      - name: ORDERS
        description: "Tabla original de PEDIDOS"
      - name: PART
        description: "Tabla original de PARTES"   
      - name: PARTSUPP
        description: "Tabla original de PARTES DE PROVEEDORES"      
      - name: REGION
        description: "Tabla original de REGIONES"
      - name: SUPPLIER
        description: "Tabla original de PROVEEDORES"