version: 2

sources:
  - name: src
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    # config:
    #   materialized: "table"
    tables:
      - name: CUSTOMER
        description: "Tabla original de CLIENTES"
      - name: LINEITEM
        description: "Tabla original de LINEAS DE PEDIDOS"
      - name: NATION
        description: "Tabla original de PAISES"
      - name: ORDERS
        description: "Tabla original de PEDIDOS"
      - name: PART
        description: "Tabla original de PARTES"
      - name: PARTSUPP
        description: "Tabla original de PARTES DE PROVEEDORES"
      - name: REGION
        description: "Tabla original de REGIONES"
      - name: SUPPLIER
        description: "Tabla original de PROVEEDORES"

  - name: stg
    database: SDGVAULTMART
    schema: DBT_SDGVAULT
    #config:
    #  materialized: "table"
    tables:
      - name: STG_CLIENTES
      - name: STG_PAISES
      - name: STG_PARTES
      - name: STG_PROVEEDORES
      - name: STG_REGIONES
      - name: STG_LINEAS_PEDIDO
      - name: STG_PEDIDOS
      - name: STG_PARTES_PROVEEDOR

  - name: raw
    database: SDGVAULTMART
    schema: DBT_SDGVAULT
    tables:
      - name: HUB_CLIENTES
      - name: HUB_PAISES
      - name: HUB_PARTES
      - name: HUB_PEDIDOS
      - name: HUB_PROVEEDORES
      - name: HUB_REGIONES
      - name: HUB_PARTES_PROVEEDORES
      - name: HUB_LINEAS_PEDIDOS
      
      
