version: 2

sources:
  - name: src
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    # config:
    #   materialized: "table"
    tables:
      - name: CUSTOMER
        description: "Tabla original de CLIENTES"
      - name: LINEITEM
        description: "Tabla original de LINEAS DE PEDIDOS"
      - name: NATION
        description: "Tabla original de PAISES"
      - name: ORDERS
        description: "Tabla original de PEDIDOS"
      - name: PART
        description: "Tabla original de PARTES"
      - name: PARTSUPP
        description: "Tabla original de PARTES DE PROVEEDORES"
      - name: REGION
        description: "Tabla original de REGIONES"
      - name: SUPPLIER
        description: "Tabla original de PROVEEDORES"

  - name: stg
    # Corresponde con la capa LANDING DEL MODELO FISICO DEL ARQUETIPO MEDALLIUM
    # Tiene las tablas en bruto ingestadas desde el origen TPCH_SF1 de Snowflake
    database: SDGVAULTMART
    schema: DBT_SDGVAULT
    #config:
    #  materialized: "table"
    tables:
      - name: STG_CLIENTES
      - name: STG_PAISES
      - name: STG_PARTES
      - name: STG_PROVEEDORES
      - name: STG_REGIONES
      - name: STG_LINEAS_PEDIDO
      - name: STG_PEDIDOS
      - name: STG_PARTES_PROVEEDOR      
      - name: CLIENTES_ELT
        description: "Tabla de carga de CLIENTES via CSV de manera incremental"     
      - name: PAISES_ELT
        description: "Tabla de carga de PAISES via CSV de manera incremental"     
      - name: PEDIDOS_ELT
        description: "Tabla de carga de PAISES via CSV de manera incremental"    

  - name: raw
    # RAW DATA VAULT: Capa que contiene el modelo base de datos histórico y auditable, diseñado para capturar los datos tal como llegan desde las fuentes, 
    #  sin transformaciones de negocio. Implemente estructuras  HUBs, LINKs y SATÉLITES, y permite la trazabilidad completa desde los datos brutos
    # Para estandarización, semántica, calidad técnica, metadatado y baja lógica de complejidad de negocio
    # Ubicación : Capa Bronze
    database: SDGVAULTMART
    schema: DBT_SDGVAULT_BRONZE
    tables:
      - name: HUB_CLIENTES
        description: "Tabla HUB que almacena las claves únicas de negocio de los CLIENTES consolidando su identificación desde diferentes fuentes de datos."      
      - name: HUB_PAISES
        description: "Tabla HUB que almacena las claves únicas de negocio de los PAISES consolidando su identificación desde diferentes fuentes de datos."
      - name: HUB_PARTES
        description: "Tabla HUB que almacena las claves únicas de negocio de los PARTES consolidando su identificación desde diferentes fuentes de datos."
      - name: HUB_PEDIDOS
        description: "Tabla HUB que almacena las claves únicas de negocio de los PEDIDOS consolidando su identificación desde diferentes fuentes de datos."
      - name: HUB_PROVEEDORES
        description: "Tabla HUB que almacena las claves únicas de negocio de los PROVEEDORES consolidando su identificación desde diferentes fuentes de datos."
      - name: HUB_REGIONES
        description: "Tabla HUB que almacena las claves únicas de negocio de los REGIONES (Continentes) consolidando su identificación desde diferentes fuentes de datos."
      - name: HUB_LINEAS_PEDIDOS
        description: "Tabla HUB que almacena las claves únicas de negocio de las LINEAS DE PEDIDO consolidando su identificación desde diferentes fuentes de datos."
      - name: LNK_CLIENTES_PEDIDOS
        description: "Tabla LINK que representa la relación entre CLIENTES Y PEDIDOS, consolidando vínculos transaccionales entre ambas entidades"
      - name: LNK_PAISES_CLIENTES
        description: "Tabla LINK que representa la relación entre PAISES Y CLIENTES, consolidando vínculos transaccionales entre ambas entidades"
      - name: LNK_PAISES_PROVEEDORES
        description: "Tabla LINK que representa la relación entre PAÍSES Y PROVEEDORES, consolidando vínculos transaccionales entre ambas entidades"
      - name: LNK_PARTES_LINEAS_PEDIDOS
        description: "Tabla LINK que representa la relación entre PARTES Y LÍNEAS DE PEDIDOS, consolidando vínculos transaccionales entre ambas entidades"
      - name: LNK_PEDIDOS_LINEAS_PEDIDOS
        description: "Tabla LINK que representa la relación entre PEDIDOS Y LÍNEAS DE PEDIDOS, consolidando vínculos transaccionales entre ambas entidades"
      - name: LNK_PROVEEDORES_LINEAS_PEDIDOS
        description: "Tabla LINK que representa la relación entre PROVEEDORES Y LÍNEAS DE PEDIDOS, consolidando vínculos transaccionales entre ambas entidades"
      - name: LNK_PROVEEDORES_PARTES
        description: "Tabla LINK que representa la relación entre PROVEEDORES Y PARTES, consolidando vínculos transaccionales entre ambas entidades"
      - name: LNK_REGIONES_PAISES
        description: "Tabla LINK que representa la relación entre REGIONES Y PAISES, consolidando vínculos transaccionales entre ambas entidades"
      - name: SAT_CLIENTES_CONTACTO      
        description: "Tabla SATÉLITE que almacena los datos de CONTACTO DE CLIENTES, permitiendo la trazabilidad de sus cambios históricos."
      - name: SAT_CLIENTES_CUENTA
        description: "Tabla SATÉLITE que almacena los datos de CUENTA DE CLIENTES, permitiendo la trazabilidad de sus cambios históricos."
      - name: SAT_LINEAS_PEDIDOS
        description: "Tabla SATÉLITE que almacena los datos de LINEAS DE PEDIDOS, permitiendo la trazabilidad de sus cambios históricos."
      - name: SAT_PAISES
        description: "Tabla SATÉLITE que almacena los datos de PAISES, permitiendo la trazabilidad de sus cambios históricos."
      - name: SAT_PARTES
        description: "Tabla SATÉLITE que almacena los datos de PARTES, permitiendo la trazabilidad de sus cambios históricos."
      - name: SAT_PARTES_PROVEEDORES
        description: "Tabla SATÉLITE que almacena los datos de PARTES DE PROVEEDORES, permitiendo la trazabilidad de sus cambios históricos."
      - name: SAT_PEDIDOS
        description: "Tabla SATÉLITE que almacena los datos de PEDIDOS, permitiendo la trazabilidad de sus cambios históricos."
      - name: SAT_PROVEEDORES
        description: "Tabla SATÉLITE que almacena los datos de PROVEEDORES, permitiendo la trazabilidad de sus cambios históricos."
      - name: SAT_REGIONES
        description: "Tabla SATÉLITE que almacena los datos de REGIONES (continentes), permitiendo la trazabilidad de sus cambios históricos."

  - name: business
    # BUSINESS DATA VAULT: Capa que extiende el modelo Raw Data Vault con reglas de negocio, integraciones semánticas y lógica derivada que no altera los datos fuente. 
    # Incluye objetos como BRIDGE, PIT y SATs derivados con lógica de negocio aplicada (por ejemplo, consolidaciones, deduplicaciones, enriquecimientos).
    # Ubicación: También en Bronze (en algunos casos considerada "Silver lógica").
    database: SDGVAULTMART
    schema: DBT_SDGVAULT_BRONZE
    tables:
      - name: PIT_CLIENTES
        description: "Tabla PIT para recuperar el estado histórico de los atributos de CLIENTES en una fecha específica a partir de sus satélites."
      - name: BRIDGE_PEDIDOS
        description: "Tabla BRIDGE conteniendo la relación entre PEDIDOS Y CLIENTES en forma jerárquica para facilitar análisis de históricos completos"


  - name: mart
    # RAW DATA MART: Capa dimensional derivada directamente del Raw Data Vault sin aplicar reglas complejas de negocio. 
    # Estructura los datos en modelos tipo estrella (Dimensiones y Hechos) listos para análisis de negocio, pero sin romper el linaje de la información técnica  
    # Ubicación: Silver
    database: SDGVAULTMART
    schema: DBT_SDGVAULT_SILVER
    tables:
      - name: DIM1_PAISES
        description: "Tabla de dimensión Tipo 1 de PAISES"
      - name: DIM2_CLIENTES
        description: "Tabla de dimensión Tipo 2 de CLIENTES"
      - name: FACT_CLIENTES_CUENTAS
        description: "Tabla de Hechoi Tipo 2 de CLIENTES"

  - name: infomart
    # INFORMATION MART:Capa final orientada al consumidor, donde los datos están enriquecidos, gobernados y estructurados para casos de uso específicos. 
    # Pueden usar tablas de la capa Business Data Vault. Aquí se aplican reglas de negocio completas, jerarquías, métricas calculadas, etc. 
    # Ubicación: Gold
    database: SDGVAULTMART
    schema: DBT_SDGVAULT_GOLD
    tables:
      - name: DIM1_CLIENTES
        description: "Tabla de dimensión Tipo 1 de CLIENTES"
      - name: FACT_CLIENTES_PEDIDOS
        description: "Tabla de hechos de CLIENTES PEDIDOS con métricas calculadas"

